# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7c7f0f6dd42ba34daea8c133ce7b77bc0388570de0feb99b413949283a6c9a6a0af0d858e64e00a2ccbc4d361349a1bd711076cc3d35d8e76872efe1562e978

test:
  secret_key_base: 0c475a0a479c8c2f44d2ad65773e5ee6806829db82ed49300e3f7aef3fd29161915531f706a27e4d54f9de421bf595bbe234414c01ff1638c05d41a8e57d1a7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
